### ISSUE TITLE
Problem downloading a post containing both photo and video

### ISSUE THREAD

**Issue by stefins** [IamStefin/Instagram-Image-Downloader-Bot#6]

**Comment by OsamaFathy** [comment]
I would like to work on this one.

My solution would be to ignore the meta tags and instead use `display_url` and `video_url` properties in the html_doc.

**Comment by pompierninja** [comment]
Hello, can you please provide us an example of a post, I'd like to work on it. Ty

mo.

**Comment by stefins** [comment]
> Hello, can you please provide us an example of a post, I'd like to work on it. Ty
> 
> mo.

@angulartist  The Instagram account of github is having a post  https://www.instagram.com/p/B27UTWZDlZY/ . when we try to download the file only the picture is downloading not the videos.

**Comment by pompierninja** [comment]
ok thanks, can u assign me this issue?

mo

**Comment by pompierninja** [comment]
I made a function that handles both images and videos here https://github.com/IamStefin/Instagram-Image-Downloader/pull/19

I wasnt sure about the "og:video" tags so I just used the JSON thing returned in the body response

**Comment by stefins** [comment]
Great, Thanks for the PR :)
